[package]
name = "chico"
version = "0.0.1"
edition = "2024"
description = "A toy C compiler, based on the book 'Writing a C Compiler' by Nora Sandler"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
regex = "1.11"
